<!DOCTYPE html>
<html lang="en">
<head>
    <title>Subscribe to NZO Hunting Magazine</title>
    <meta NAME="Description" CONTENT="Supporting Hunters for over 75 years - your No.1 magazine for hunting stories, where to hunt, trophy pictures, product tests, guns and shooting, prizes and giveaways.">
<meta NAME="Keywords" CONTENT="NZ OUTDOOR HUNTING MAGAZINE, hunter, hunt, hunting, new zealand,outdoor,stag,deer,bow hunting, product tests, trophies, guns, shooting, giveaways, Red deer, sika, fallow, whitetail, rusa, sambar, wapiti, chamois, tahr, wild pigs, bird shooting">
<meta NAME="Copyright" CONTENT="NZ OUTDOOR HUNTING MAGAZINE 2013. All rights reserved">
<meta NAME="Publisher" CONTENT="eRiQ creations">
<meta NAME="Owner" CONTENT="NZ OUTDOOR HUNTING MAGAZINE">
<meta NAME="Distribution" CONTENT="Global">
<meta NAME="Language" CONTENT="English">
<meta NAME="Rating" CONTENT="General">
<meta NAME="Robots" CONTENT="follow,index">
<meta NAME="Revisit" CONTENT="4 days">

    <link rel="stylesheet" href="/css/style.css">
    <link rel="stylesheet" href="/css/subscribe.css">
    <script src="/js/jquery-1.6.4.min.js"></script>
    <script src="/js/cufon-yui.js"></script>
    <script src="/js/Franklin_Gothic_Medium_400.font.js"></script>
    <script src="/js/cufon-replace.js"></script>
    <script src="/js/script.js"></script>
	<!--[if lt IE 7]>
  		<div class='aligncenter'><a href="/http://www.microsoft.com/windows/internet-explorer/default.aspx?ocid=ie6_countdown_bannercode"><img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg"border="0"></a></div>  
 	<![endif]-->
    <!--[if lt IE 9]>
   		<script src="/js/html5.js"></script>
  		<link rel="stylesheet" href="//css/ie.css"> 
	<![endif]-->
</head>
<body>
<div class="bg">
    <!--==============================header=================================-->
    <header>
        <div class="main">
            <h1><a href="/">NZO HUNTING</a></h1>
            <nav>
                <ul class="sf-menu">
                  <li><a href="/">home</a>
                    </li>
                    <li><a href="/nz_outdoor_hunting_team.html">Our TEAM</a></li>
                    <li class="current"><a href="/subscribe">SUBSCRIBE</a></li>
                    <li><a href="/nz_outdoor_hunting_photopages.html">PHOTO PAGES</a></li>
                    <li><a href="/nz_outdoor_hunting_productreviews.html">PRODUCT REVIEWS</a></li>
                    <li><a href="/nz_outdoor_hunting_contacts.html">Contact US</a></li>
                </ul>
            </nav>
            <div class="clear"></div>
        </div>
    </header>
    <!--==============================content================================-->
    <section id="content">
        <div class="main">
